services:
  jekyll-site:
    image: jekyll-site
    build: .
    volumes: [ .:/usr/src/app:z ]
    ports: [ 4000:4000 ]
    user: 1000:1000
    environment: [ JEKYLL_ENV=podman ]
    command: jekyll serve -H 0.0.0.0 -w --config _config.yml,_config_docker.yml
userns_mode: keep-id
